//! OpenCode sessions, stored as rows in one SQLite database:
//! `$XDG_DATA_HOME/opencode/opencode.db` (default `~/.local/share/opencode`),
//! with `OPENCODE_DB` overriding the file the way OpenCode itself honors.

use super::{
    Fingerprint, RefNamespaces, SessionCache, SessionLaunch, SessionLauncher, SessionProvider,
    SessionRoot, SessionStorage, SessionStub, SourceLabels,
};
use crate::cli::DebugLevel;
use crate::error::{AppError, Result};
use crate::history::format::opencode::{
    self, OPENCODE_DB, database_error, decode_ref, session_ref,
};
use crate::history::format::{self, SessionFormat};
use crate::history::{Conversation, Source, parser};
use rusqlite::{Connection, OpenFlags, OptionalExtension};
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

pub struct OpenCodeProvider;

impl SessionProvider for OpenCodeProvider {
    fn source(&self) -> Source {
        Source::OpenCode
    }

    fn labels(&self) -> SourceLabels {
        SourceLabels {
            name: "opencode",
            list: "OC",
            display: "OpenCode",
        }
    }

    fn ref_namespaces(&self) -> RefNamespaces {
        RefNamespaces {
            conversation: Some("agent-opencode-v1"),
            project: "agent-opencode-project-v1",
        }
    }

    fn storage(&self) -> Option<&dyn SessionStorage> {
        Some(&OpenCodeStorage)
    }

    fn format(&self) -> Option<&dyn SessionFormat> {
        Some(&OPENCODE_DB)
    }

    fn launcher(&self) -> &dyn SessionLauncher {
        &OpenCodeLauncher
    }

    /// A title is a column of the session row. The update also bumps
    /// `time_updated`, which the discovery fingerprint reads, so a warm cache
    /// sees the rename on the next load. OpenCode stores no custom-title
    /// marker; renamed and autogenerated titles project the same way.
    fn rename_session(&self, path: &Path, title: &str) -> Result<()> {
        format::require_owned_transcript(Source::OpenCode, path)?;
        let reference = owned_ref(path)?;
        let connection = open_read_write(&reference.database)?;
        let cleaned = title.replace(['\r', '\n'], " ").trim().to_owned();
        connection
            .execute(
                "UPDATE session SET title = ?1, time_updated = ?2 WHERE id = ?3",
                rusqlite::params![cleaned, now_millis(), reference.session_id],
            )
            .map_err(|error| database_error(&reference.database, &error))?;
        Ok(())
    }

    /// A session is its rows. The schema cascades `message` and `part`
    /// deletion from the session row, so one delete removes the whole
    /// conversation — with foreign keys switched on for this connection,
    /// since SQLite leaves them off by default.
    fn delete_session(&self, path: &Path) -> Result<usize> {
        format::require_owned_transcript(Source::OpenCode, path)?;
        let reference = owned_ref(path)?;
        let connection = open_read_write(&reference.database)?;
        connection
            .pragma_update(None, "foreign_keys", "ON")
            .map_err(|error| database_error(&reference.database, &error))?;
        connection
            .execute("DELETE FROM session WHERE id = ?1", [&reference.session_id])
            .map_err(|error| database_error(&reference.database, &error))?;
        // Rows, not files, and one session is one row however many messages
        // and parts cascade from it.
        Ok(1)
    }

    /// A session is a row keyed by its id; an archived one is not listed, and
    /// not resolved either. The `ses_` prefix keeps an ordinary query from
    /// opening the database.
    fn resolve_session_id(&self, session_id: &str) -> Result<Option<PathBuf>> {
        if !session_id.starts_with("ses_") {
            return Ok(None);
        }
        for root in OpenCodeStorage.roots()? {
            if let Some(locator) = live_session_in(&root.path, session_id)? {
                return Ok(Some(locator));
            }
        }
        Ok(None)
    }
}

/// The locator for `session_id` in `database`, when a row holds it unarchived.
fn live_session_in(database: &Path, session_id: &str) -> Result<Option<PathBuf>> {
    if !database.is_file() {
        return Ok(None);
    }
    let connection = opencode::open_read_only(database)?;
    let stored = connection
        .query_row(
            "SELECT 1 FROM session WHERE id = ?1 AND time_archived IS NULL",
            [session_id],
            |_| Ok(()),
        )
        .optional()
        .map_err(|error| database_error(database, &error))?;
    Ok(stored.map(|()| session_ref(database, session_id)))
}

/// The guard has vouched for `path`; decoding it again can only fail if the
/// database vanished in between, which reports as the session it no longer
/// holds.
fn owned_ref(path: &Path) -> Result<opencode::SessionRef> {
    decode_ref(path).ok_or_else(|| AppError::SessionNotFound(path.display().to_string()))
}

/// Read-write without `CREATE`: creating a database is OpenCode's job, never
/// this browser's. A database that vanished since the ownership guard fails
/// here as unable-to-open rather than leaving an empty file behind.
fn open_read_write(database: &Path) -> Result<Connection> {
    let connection = Connection::open_with_flags(
        database,
        OpenFlags::SQLITE_OPEN_READ_WRITE | OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )
    .map_err(|error| database_error(database, &error))?;
    opencode::configure(database, &connection)?;
    Ok(connection)
}

fn now_millis() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_millis() as i64
}

struct OpenCodeStorage;

impl SessionStorage for OpenCodeStorage {
    fn source(&self) -> Source {
        Source::OpenCode
    }

    fn cache(&self) -> SessionCache {
        SessionCache {
            directory: "opencode",
            magic: *b"OCHIST01",
            schema_version: 3,
        }
    }

    fn roots(&self) -> Result<Vec<SessionRoot>> {
        let home = home::home_dir().ok_or_else(|| {
            AppError::Io(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Could not determine home directory",
            ))
        })?;
        Ok(vec![
            SessionRoot::new(database_path_from(
                std::env::var("OPENCODE_DB").ok().as_deref(),
                std::env::var_os("XDG_DATA_HOME")
                    .map(PathBuf::from)
                    .as_deref(),
                &home,
            ))
            .in_agent_tree(),
        ])
    }

    /// One query fingerprints every session: the payload bytes of its
    /// messages and parts plus its title's length, and the newest
    /// `time_updated` across the session and its rows. Content-derived, so
    /// the cache does not depend on when OpenCode chooses to touch the
    /// session row — except for a rename to a same-length title that bumps
    /// nothing, which stays stale until the session's next activity.
    /// Archived sessions are not sessions to browse, matching the Codex
    /// `archived_sessions/` line. A missing database is an agent the user
    /// has not installed: an absence, not a failure.
    fn discover(&self, root: &SessionRoot) -> Result<Vec<SessionStub>> {
        if !root.path.is_file() {
            return Ok(Vec::new());
        }
        let connection = opencode::open_read_only(&root.path)?;
        let mut statement = connection
            .prepare(
                "SELECT s.id,
                        LENGTH(s.title)
                          + COALESCE((SELECT SUM(LENGTH(m.data)) FROM message m
                                      WHERE m.session_id = s.id), 0)
                          + COALESCE((SELECT SUM(LENGTH(p.data)) FROM part p
                                      WHERE p.session_id = s.id), 0),
                        MAX(s.time_updated,
                            COALESCE((SELECT MAX(m.time_updated) FROM message m
                                      WHERE m.session_id = s.id), 0),
                            COALESCE((SELECT MAX(p.time_updated) FROM part p
                                      WHERE p.session_id = s.id), 0))
                 FROM session s
                 WHERE s.time_archived IS NULL
                 ORDER BY s.id",
            )
            .map_err(|error| database_error(&root.path, &error))?;
        let rows = statement
            .query_map([], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, i64>(1)?,
                    row.get::<_, i64>(2)?,
                ))
            })
            .map_err(|error| database_error(&root.path, &error))?;
        let mut stubs = Vec::new();
        for row in rows {
            let (session_id, size, updated_ms) =
                row.map_err(|error| database_error(&root.path, &error))?;
            stubs.push(SessionStub {
                locator: session_ref(&root.path, &session_id),
                cache_key: session_id,
                fingerprint: Fingerprint {
                    size: size.max(0) as u64,
                    modified: Some(UNIX_EPOCH + Duration::from_millis(updated_ms.max(0) as u64)),
                },
            });
        }
        Ok(stubs)
    }

    fn parse_session(
        &self,
        locator: PathBuf,
        root: &SessionRoot,
        modified: Option<SystemTime>,
        debug_level: Option<DebugLevel>,
    ) -> Result<Option<Conversation>> {
        warn_when_schema_outruns_reader(&root.path, debug_level);
        parser::process_session_file(locator, &OPENCODE_DB, modified, debug_level)
    }

    /// Every session is read in full, however large: the biggest sessions
    /// are the most valuable to search, and skipping one would delist it.
    fn max_session_bytes(&self) -> Option<u64> {
        None
    }
}

/// Warn once per process when the database has applied a schema migration
/// this reader was never verified against — the one drift signal OpenCode
/// records. Advisory only: additive migrations are the common case, a
/// column this reader misses already fails its query loudly, and
/// payload-shape changes inside `data` ship without a migration and are
/// not detectable here at all. What the warning buys is an explanation
/// when a newer OpenCode's sessions project incompletely.
fn warn_when_schema_outruns_reader(database: &Path, debug_level: Option<DebugLevel>) {
    if debug_level.is_none() {
        return;
    }
    static REPORTED: std::sync::Once = std::sync::Once::new();
    REPORTED.call_once(|| {
        let Ok(connection) = opencode::open_read_only(database) else {
            return;
        };
        if let Some(newest) = opencode::newest_unverified_migration(&connection) {
            crate::debug::warn(
                debug_level,
                &format!(
                    "{}: schema migration {newest} is newer than this reader was verified \
                     against ({}); sessions may project incompletely",
                    database.display(),
                    opencode::NEWEST_VERIFIED_MIGRATION
                ),
            );
        }
    });
}

/// The database OpenCode reads and writes: `OPENCODE_DB` verbatim when
/// absolute, under the data directory when relative, else
/// `<data>/opencode.db` — the same resolution OpenCode's own
/// `database.ts` performs. Channel-specific databases
/// (`opencode-<channel>.db`) are not searched; the channel is chosen at
/// install time and is not observable from here.
fn database_path_from(
    opencode_db: Option<&str>,
    xdg_data_home: Option<&Path>,
    home: &Path,
) -> PathBuf {
    let data_dir = xdg_data_home
        .filter(|path| !path.as_os_str().is_empty())
        .map(|path| path.join("opencode"))
        .unwrap_or_else(|| home.join(".local").join("share").join("opencode"));
    match opencode_db.filter(|value| !value.is_empty()) {
        Some(value) => {
            let path = PathBuf::from(value);
            if path.is_absolute() {
                path
            } else {
                data_dir.join(path)
            }
        }
        None => data_dir.join("opencode.db"),
    }
}

/// OpenCode resumes and forks by session id — the locator's stem — with
/// resume run in the session's working directory.
struct OpenCodeLauncher;

impl SessionLauncher for OpenCodeLauncher {
    fn resume_command(&self, launch: &SessionLaunch) -> Result<std::process::Command> {
        let mut command = std::process::Command::new("opencode");
        command.arg("--session").arg(session_id_of(launch.path)?);
        if let Some(project_path) = launch.project_path {
            command.current_dir(project_path);
        }
        Ok(command)
    }

    /// A fork runs where the user is now, not where the original session
    /// ran: the branch belongs to the current project.
    fn fork_command(&self, launch: &SessionLaunch) -> Result<std::process::Command> {
        let mut command = std::process::Command::new("opencode");
        command
            .arg("--session")
            .arg(session_id_of(launch.path)?)
            .arg("--fork");
        Ok(command)
    }
}

fn session_id_of(path: &Path) -> Result<String> {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .filter(|stem| stem.starts_with(opencode::SESSION_ID_PREFIX))
        .map(str::to_owned)
        .ok_or_else(|| {
            AppError::ConfigError(format!(
                "{} does not name an OpenCode session",
                path.display()
            ))
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::history::format::opencode::fixture::{self, SessionSpec};
    use std::ffi::OsStr as StdOsStr;

    fn database_in(directory: &Path) -> PathBuf {
        let database = directory.join("opencode.db");
        fixture::create_database(&database);
        database
    }

    fn discovered(database: &Path) -> Vec<SessionStub> {
        OpenCodeStorage
            .discover(&SessionRoot::new(database))
            .unwrap()
    }

    #[test]
    fn the_database_is_opencode_db_or_its_override() {
        let home = Path::new("/home/user");
        assert_eq!(
            database_path_from(None, None, home),
            home.join(".local/share/opencode/opencode.db")
        );
        assert_eq!(
            database_path_from(None, Some(Path::new("/xdg/data")), home),
            Path::new("/xdg/data/opencode/opencode.db")
        );
        assert_eq!(
            database_path_from(Some("/elsewhere/history.db"), None, home),
            Path::new("/elsewhere/history.db")
        );
        assert_eq!(
            database_path_from(Some("beta.db"), None, home),
            home.join(".local/share/opencode/beta.db"),
            "a relative override joins the data directory, as OpenCode joins it"
        );
        assert_eq!(
            database_path_from(Some(""), None, home),
            home.join(".local/share/opencode/opencode.db"),
            "an empty override means unset"
        );
    }

    #[test]
    fn discovery_lists_live_sessions_and_skips_archived_ones() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_live");
        fixture::insert_session(
            &connection,
            &SessionSpec {
                id: "ses_archived",
                parent_id: None,
                directory: "/tmp/opencode-project",
                title: "archived away",
                created_ms: 1755000000000i64,
                updated_ms: 1755000000000i64,
                archived_ms: Some(1755000500000i64),
            },
        );
        drop(connection);

        let stubs = discovered(&database);

        assert_eq!(
            stubs
                .iter()
                .map(|stub| stub.cache_key.as_str())
                .collect::<Vec<_>>(),
            vec!["ses_live"],
            "an archived session is not a session to browse"
        );
        assert_eq!(stubs[0].locator, database.join("ses_live.jsonl"));
        assert!(stubs[0].fingerprint.modified.is_some());
    }

    #[test]
    fn a_missing_database_discovers_nothing() {
        let directory = tempfile::tempdir().unwrap();
        let stubs = OpenCodeStorage
            .discover(&SessionRoot::new(directory.path().join("never-created.db")))
            .unwrap();
        assert!(stubs.is_empty());
    }

    /// The fingerprint is the cache's change detector: new rows and renames
    /// must move it, an untouched database must not.
    #[test]
    fn the_fingerprint_moves_with_content_and_title_but_not_on_its_own() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_fingerprint");

        let first = discovered(&database)[0].fingerprint;
        let second = discovered(&database)[0].fingerprint;
        assert_eq!(first, second, "an untouched database fingerprints alike");

        fixture::insert_message(
            &connection,
            "msg_more",
            "ses_fingerprint",
            1755000600000i64,
            &serde_json::json!({ "role": "user", "time": { "created": 1755000600000i64 } }),
        );
        let after_append = discovered(&database)[0].fingerprint;
        assert_ne!(first, after_append, "appended rows must reparse");

        OpenCodeProvider
            .rename_session(&database.join("ses_fingerprint.jsonl"), "renamed")
            .unwrap();
        let after_rename = discovered(&database)[0].fingerprint;
        assert_ne!(after_append, after_rename, "a rename must reparse");
    }

    #[test]
    fn resume_and_fork_take_the_session_id_from_the_locator() {
        let path = PathBuf::from("/data/opencode/opencode.db/ses_launch.jsonl");
        let project = PathBuf::from("/tmp/project");
        let launch = SessionLaunch {
            path: &path,
            project_path: Some(&project),
            configured_args: &["--claude-only".to_owned()],
        };
        let launcher = Source::OpenCode.provider().launcher();

        let resume = launcher.resume_command(&launch).unwrap();
        assert_eq!(resume.get_program(), StdOsStr::new("opencode"));
        assert_eq!(
            resume.get_args().collect::<Vec<_>>(),
            vec![StdOsStr::new("--session"), StdOsStr::new("ses_launch")],
            "opencode resumes by session id and must not inherit Claude's configured arguments"
        );
        assert_eq!(resume.get_current_dir(), Some(project.as_path()));

        let fork = launcher.fork_command(&launch).unwrap();
        assert_eq!(
            fork.get_args().collect::<Vec<_>>(),
            vec![
                StdOsStr::new("--session"),
                StdOsStr::new("ses_launch"),
                StdOsStr::new("--fork")
            ]
        );
        assert_eq!(
            fork.get_current_dir(),
            None,
            "a fork runs in the current directory"
        );
    }

    #[test]
    fn rename_updates_the_title_and_preserves_the_rest_of_the_row() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_rename");
        drop(connection);
        let locator = database.join("ses_rename.jsonl");

        OpenCodeProvider
            .rename_session(&locator, "renamed\nOpenCode")
            .unwrap();

        let connection = Connection::open(&database).unwrap();
        let (title, slug, version): (String, String, String) = connection
            .query_row(
                "SELECT title, slug, version FROM session WHERE id = 'ses_rename'",
                [],
                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
            )
            .unwrap();
        assert_eq!(title, "renamed OpenCode");
        assert_eq!(
            slug, "ses_rename",
            "columns this browser does not own survive"
        );
        assert_eq!(version, "1.0.0-fixture");
        drop(connection);

        let reparsed = OPENCODE_DB.parse_transcript(&locator).unwrap().unwrap();
        assert_eq!(reparsed.title.as_deref(), Some("renamed OpenCode"));
    }

    #[test]
    fn delete_cascades_to_the_sessions_messages_and_parts() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_doomed");
        fixture::standard_session(&connection, "ses_kept");
        drop(connection);

        OpenCodeProvider
            .delete_session(&database.join("ses_doomed.jsonl"))
            .unwrap();

        let connection = Connection::open(&database).unwrap();
        let count = |sql: &str| -> i64 { connection.query_row(sql, [], |row| row.get(0)).unwrap() };
        assert_eq!(
            count("SELECT COUNT(*) FROM session WHERE id = 'ses_doomed'"),
            0
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM message WHERE session_id = 'ses_doomed'"),
            0,
            "messages cascade with their session"
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM part WHERE session_id = 'ses_doomed'"),
            0,
            "parts cascade with their session"
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM session WHERE id = 'ses_kept'"),
            1
        );
    }

    #[test]
    fn the_write_path_never_creates_a_database() {
        let directory = tempfile::tempdir().unwrap();
        let vanished = directory.path().join("vanished.db");

        assert!(open_read_write(&vanished).is_err());
        assert!(
            !vanished.exists(),
            "an absent database must fail the write, not be created by it"
        );
    }

    #[test]
    fn a_file_opencode_does_not_own_survives_delete() {
        let directory = tempfile::tempdir().unwrap();
        let pi = directory.path().join("session.jsonl");
        std::fs::copy(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/pi/v3-branched.jsonl"),
            &pi,
        )
        .unwrap();

        assert!(OpenCodeProvider.delete_session(&pi).is_err());
        assert!(pi.exists());

        let database = database_in(directory.path());
        assert!(
            OpenCodeProvider
                .delete_session(&database.join("ses_absent.jsonl"))
                .is_err(),
            "a session the database does not hold is not OpenCode's to delete"
        );
    }

    /// A rename rewrites only database rows; the fingerprint carries it to
    /// the next load, with no sidecar overlay to fall back on.
    #[test]
    fn a_rename_reaches_the_next_load_through_a_warm_cache() {
        use crate::history::cache::SessionCacheStore;
        use crate::history::provider::load_sessions_with_cache;

        let directory = tempfile::tempdir().unwrap();
        let cache_base = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_warm");
        drop(connection);

        let storage = crate::history::provider::storage::RootedStorage {
            inner: OpenCodeStorage,
            root: SessionRoot::new(&database).in_agent_tree(),
        };
        let cache = SessionCacheStore::under(cache_base.path(), storage.cache());
        let first = load_sessions_with_cache(&storage, &cache, false, None).unwrap();
        assert_eq!(
            first[0].custom_title.as_deref(),
            Some("fixture generated title")
        );

        OpenCodeProvider
            .rename_session(&database.join("ses_warm.jsonl"), "fresh name")
            .unwrap();

        let second = load_sessions_with_cache(&storage, &cache, false, None).unwrap();
        assert_eq!(second[0].custom_title.as_deref(), Some("fresh name"));
    }

    #[test]
    fn a_session_id_resolves_to_its_row_and_an_archived_one_does_not() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_live");
        fixture::insert_session(
            &connection,
            &SessionSpec {
                id: "ses_archived",
                parent_id: None,
                directory: "/tmp/opencode-project",
                title: "archived away",
                created_ms: 1755000000000i64,
                updated_ms: 1755000000000i64,
                archived_ms: Some(1755000500000i64),
            },
        );
        drop(connection);

        assert_eq!(
            live_session_in(&database, "ses_live").unwrap(),
            Some(database.join("ses_live.jsonl"))
        );
        assert_eq!(live_session_in(&database, "ses_archived").unwrap(), None);
        assert_eq!(live_session_in(&database, "ses_absent").unwrap(), None);
    }

    #[test]
    fn a_query_without_the_session_prefix_resolves_without_opening_a_database() {
        assert_eq!(
            OpenCodeProvider.resolve_session_id("deployment").unwrap(),
            None
        );
    }
}
