//! OpenCode sessions, stored as rows in one SQLite database:
//! `$XDG_DATA_HOME/opencode/opencode.db` (default `~/.local/share/opencode`),
//! with `OPENCODE_DB` overriding the file the way OpenCode itself honors.

use super::sqlite::{
    self, SESSION_DATABASE_CANNOT_BE_OPENED, SESSION_DATABASE_CANNOT_BE_READ, SchemaPin,
    database_error,
};
use super::subagents::SubagentForest;
use super::{
    Deleted, DiscoveredSessions, Fingerprint, RefNamespaces, ResolvedSession, SessionCache,
    SessionLaunch, SessionLauncher, SessionProvider, SessionRoot, SessionStorage, SessionStub,
    SourceLabels,
};
use crate::cli::DebugLevel;
use crate::error::{AppError, Result};
use crate::history::format::opencode::{self, OPENCODE_DB, decode_ref, session_ref};
use crate::history::format::{self, SessionFormat};
use crate::history::{Conversation, Source, parser};
use rusqlite::{Connection, OpenFlags, TransactionBehavior};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Once;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

pub struct OpenCodeProvider;

impl SessionProvider for OpenCodeProvider {
    fn source(&self) -> Source {
        Source::OpenCode
    }

    fn labels(&self) -> SourceLabels {
        SourceLabels {
            name: "opencode",
            list: "OC",
            display: "OpenCode",
        }
    }

    fn ref_namespaces(&self) -> RefNamespaces {
        RefNamespaces {
            conversation: Some("agent-opencode-v1"),
            project: "agent-opencode-project-v1",
        }
    }

    fn storage(&self) -> Option<&dyn SessionStorage> {
        Some(&OpenCodeStorage)
    }

    fn format(&self) -> Option<&dyn SessionFormat> {
        Some(&OPENCODE_DB)
    }

    fn launcher(&self) -> &dyn SessionLauncher {
        &OpenCodeLauncher
    }

    /// A title is a column of the session row. The update also bumps
    /// `time_updated`, which the discovery fingerprint reads, so a warm cache
    /// sees the rename on the next load. OpenCode stores no custom-title
    /// marker; renamed and autogenerated titles project the same way.
    fn rename_session(&self, path: &Path, title: &str) -> Result<()> {
        format::require_owned_transcript(Source::OpenCode, path)?;
        let reference = owned_ref(path)?;
        let connection = open_read_write(&reference.database)
            .map_err(|error| database_error(&reference.database, &error))?;
        let cleaned = title.replace(['\r', '\n'], " ").trim().to_owned();
        connection
            .execute(
                "UPDATE session SET title = ?1, time_updated = ?2 WHERE id = ?3",
                rusqlite::params![cleaned, now_millis(), reference.session_id],
            )
            .map_err(|error| database_error(&reference.database, &error))?;
        Ok(())
    }

    /// A session is its rows, and a sub-agent session is a row of its own
    /// that only an index links to its parent — no foreign key, so nothing
    /// cascades between sessions and a sub-agent session would outlive its
    /// parent as a session of its own. One immediate transaction finds and
    /// deletes the session and its sub-agent sessions, so a running OpenCode
    /// cannot add one between the two steps. Delete reads the sub-agent
    /// sessions from the same rows the list does, so a database it cannot
    /// use fails with the list's reason before any row is removed.
    fn delete_session(&self, path: &Path) -> Result<Deleted> {
        format::require_owned_transcript(Source::OpenCode, path)?;
        let reference = owned_ref(path)?;
        let database = &reference.database;
        let mut connection = open_read_write(database).map_err(|error| {
            sqlite::unusable_database(database, SESSION_DATABASE_CANNOT_BE_OPENED, &error)
        })?;
        let cannot_be_read = |error: rusqlite::Error| {
            sqlite::unusable_database(database, SESSION_DATABASE_CANNOT_BE_READ, &error)
        };
        let transaction = connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(cannot_be_read)?;
        let subagents =
            opencode::subagent_session_ids(&transaction, &reference).map_err(cannot_be_read)?;
        let fail = |error: rusqlite::Error| database_error(database, &error);
        for session_id in std::iter::once(&reference.session_id).chain(&subagents) {
            transaction
                .execute("DELETE FROM session WHERE id = ?1", [session_id])
                .map_err(fail)?;
        }
        transaction.commit().map_err(fail)?;
        // Rows, not files: one session is one row however many messages and
        // parts cascade from it.
        Ok(Deleted {
            stored_copies: 1,
            subagent_sessions: subagents.len(),
        })
    }

    /// A session is a row keyed by its id, archived or not. The `ses_` prefix
    /// keeps an ordinary query from opening the database.
    fn resolve_session_id(&self, session_id: &str) -> Result<Option<ResolvedSession>> {
        if !session_id.starts_with("ses_") {
            return Ok(None);
        }
        for root in OpenCodeStorage.roots()? {
            if let Some(stub) = stored_session_in(&root.path, session_id)? {
                return Ok(Some(ResolvedSession { root, stub }));
            }
        }
        Ok(None)
    }
}

/// The stub for `session_id` in `database`, when a row holds it: a sub-agent
/// row answers with the sub-agent rows beneath it, the one exception to every
/// filter the list applies.
///
/// Fingerprints are read for the session and the rows beneath it alone: the
/// lookup runs on a keystroke, and summing payload bytes for every session is
/// discovery's job. One read transaction, so a row OpenCode deletes between
/// the two queries cannot leave an id without a fingerprint.
fn stored_session_in(database: &Path, session_id: &str) -> Result<Option<SessionStub>> {
    if !database.is_file() {
        return Ok(None);
    }
    let mut connection = sqlite::open_session_list(database, sqlite::DEFAULT_BUSY_TIMEOUT)?;
    let cannot_be_read = |error: rusqlite::Error| {
        sqlite::unusable_database(database, SESSION_DATABASE_CANNOT_BE_READ, &error)
    };
    let transaction = connection.transaction().map_err(cannot_be_read)?;
    let forest = opencode::session_forest(&transaction).map_err(cannot_be_read)?;
    let session_id = session_id.to_owned();
    if !forest.contains(&session_id) {
        return Ok(None);
    }
    let subagents = forest.subagents_of(&session_id);
    let ids = std::iter::once(session_id.clone())
        .chain(subagents.iter().cloned())
        .collect::<Vec<_>>();
    let rows = SessionRows::read(&transaction, Some(&ids)).map_err(cannot_be_read)?;
    Ok(Some(rows.session_stub(database, &session_id, &subagents)))
}

/// Rows of the `session` table, read in one query: each session's own
/// fingerprint, and the forest of parents the rows name.
struct SessionRows {
    fingerprints: HashMap<String, Fingerprint>,
    forest: SubagentForest<String>,
}

/// A row's fingerprint is the payload bytes of its messages and parts plus
/// its title's length, and the newest `time_updated` across the session and
/// its rows. One statement for discovery and session-id lookup, so the two
/// cannot fingerprint different columns; the lookup appends a `WHERE`.
const SESSION_ROWS_SQL: &str = "SELECT s.id,
        s.parent_id,
        LENGTH(s.title)
          + COALESCE((SELECT SUM(LENGTH(m.data)) FROM message m
                      WHERE m.session_id = s.id), 0)
          + COALESCE((SELECT SUM(LENGTH(p.data)) FROM part p
                      WHERE p.session_id = s.id), 0),
        MAX(s.time_updated,
            COALESCE((SELECT MAX(m.time_updated) FROM message m
                      WHERE m.session_id = s.id), 0),
            COALESCE((SELECT MAX(p.time_updated) FROM part p
                      WHERE p.session_id = s.id), 0))
 FROM session s";

impl SessionRows {
    /// Every row, or the rows `only` names, fingerprinted in one query. The
    /// failure is SQLite's own, so the caller can word it for the list.
    fn read(connection: &Connection, only: Option<&[String]>) -> rusqlite::Result<Self> {
        let sql = match only {
            None => SESSION_ROWS_SQL.to_owned(),
            Some(ids) => {
                let placeholders = (1..=ids.len())
                    .map(|position| format!("?{position}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{SESSION_ROWS_SQL} WHERE s.id IN ({placeholders})")
            }
        };
        let mut statement = connection.prepare(&sql)?;
        let rows = statement.query_map(
            rusqlite::params_from_iter(only.unwrap_or_default()),
            |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, Option<String>>(1)?,
                    Fingerprint {
                        size: row.get::<_, i64>(2)?.max(0) as u64,
                        modified: Some(
                            UNIX_EPOCH + Duration::from_millis(row.get::<_, i64>(3)?.max(0) as u64),
                        ),
                    },
                ))
            },
        )?;
        let mut fingerprints = HashMap::new();
        let mut parents = Vec::new();
        for row in rows {
            let (session_id, parent_id, fingerprint) = row?;
            parents.push((session_id.clone(), parent_id));
            fingerprints.insert(session_id, fingerprint);
        }
        Ok(Self {
            fingerprints,
            forest: SubagentForest::new(parents),
        })
    }

    /// The stub of `session_id` with `subagents` beneath it, fingerprinted
    /// over all of them. Both come from `forest`, so every id has a row.
    fn session_stub(&self, database: &Path, session_id: &str, subagents: &[String]) -> SessionStub {
        SessionStub {
            locator: session_ref(database, session_id),
            subagents: subagents
                .iter()
                .map(|id| session_ref(database, id))
                .collect(),
            cache_key: session_id.to_owned(),
            fingerprint: Fingerprint::spanning(
                self.fingerprints[session_id],
                subagents.iter().map(|id| self.fingerprints[id.as_str()]),
            ),
        }
    }
}

/// The guard has vouched for `path`; decoding it again can only fail if the
/// database vanished in between, which reports as the session it no longer
/// holds.
fn owned_ref(path: &Path) -> Result<opencode::SessionRef> {
    decode_ref(path).ok_or_else(|| AppError::SessionNotFound(path.display().to_string()))
}

/// Read-write without `CREATE`: creating a database is OpenCode's job, never
/// this browser's. A database that vanished since the ownership guard fails
/// here as unable-to-open rather than leaving an empty file behind. Foreign
/// keys are switched on, since SQLite leaves them off by default, so a deleted
/// session's messages and parts cascade with it. The failure is SQLite's own,
/// so the caller can word it.
fn open_read_write(database: &Path) -> rusqlite::Result<Connection> {
    let connection = Connection::open_with_flags(
        database,
        OpenFlags::SQLITE_OPEN_READ_WRITE | OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )?;
    connection.busy_timeout(sqlite::DEFAULT_BUSY_TIMEOUT)?;
    connection.pragma_update(None, "foreign_keys", "ON")?;
    Ok(connection)
}

fn now_millis() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_millis() as i64
}

struct OpenCodeStorage;

impl SessionStorage for OpenCodeStorage {
    fn source(&self) -> Source {
        Source::OpenCode
    }

    fn cache(&self) -> SessionCache {
        SessionCache {
            directory: "opencode",
            magic: *b"OCHIST01",
            schema_version: 5,
        }
    }

    fn roots(&self) -> Result<Vec<SessionRoot>> {
        let home = home::home_dir().ok_or_else(|| {
            AppError::Io(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Could not determine home directory",
            ))
        })?;
        Ok(vec![
            SessionRoot::new(database_path_from(
                std::env::var("OPENCODE_DB").ok().as_deref(),
                std::env::var_os("XDG_DATA_HOME")
                    .map(PathBuf::from)
                    .as_deref(),
                &home,
            ))
            .in_agent_tree(),
        ])
    }

    /// A session is a row whose `parent_id` is null or names no row; the rows
    /// beneath it are its sub-agent rows. Each session's fingerprint spans
    /// the rows beneath it (`SESSION_ROWS_SQL`), so the cache does not depend
    /// on when OpenCode
    /// chooses to touch the session row, except for a rename to a same-length
    /// title that bumps nothing, which stays stale until the session's next
    /// activity. Archived rows are collected with the rest. A missing
    /// database is an agent the user has not installed: an absence, not a
    /// failure.
    fn discover(&self, root: &SessionRoot) -> Result<DiscoveredSessions> {
        discover_in(&root.path, sqlite::DEFAULT_BUSY_TIMEOUT)
    }

    fn parse_session(
        &self,
        stub: &SessionStub,
        root: &SessionRoot,
        debug_level: Option<DebugLevel>,
    ) -> Result<Option<Conversation>> {
        SCHEMA_PIN.warn_when_schema_outruns_reader(&root.path, debug_level);
        parser::process_session_file(stub, &OPENCODE_DB, debug_level)
    }

    /// Every session is read in full, however large: the biggest sessions
    /// are the most valuable to search, and skipping one would delist it.
    fn max_session_bytes(&self) -> Option<u64> {
        None
    }
}

/// [`OpenCodeStorage::discover`] for `database`, waiting `busy_timeout` for
/// a lock. A present database that is locked past the wait, cannot be
/// opened, or fails the query stops the OpenCode load for this launch as
/// [`AppError::SessionListUnreadable`], the failure Codex's list reports.
fn discover_in(database: &Path, busy_timeout: Duration) -> Result<DiscoveredSessions> {
    if !database.is_file() {
        return Ok(DiscoveredSessions::complete(Vec::new()));
    }
    let connection = sqlite::open_session_list(database, busy_timeout)?;
    let rows = SessionRows::read(&connection, None).map_err(|error| {
        sqlite::unusable_database(database, SESSION_DATABASE_CANNOT_BE_READ, &error)
    })?;
    let stubs = rows
        .forest
        .sessions()
        .into_iter()
        .map(|(session_id, subagents)| rows.session_stub(database, &session_id, &subagents))
        .collect();
    Ok(DiscoveredSessions::complete(stubs))
}

/// The migration journal is the one drift signal OpenCode records:
/// payload-shape changes inside `data` ship without a migration and are not
/// detectable here at all.
static SCHEMA_PIN: SchemaPin = SchemaPin {
    newest_verified: &opencode::NEWEST_VERIFIED_MIGRATION,
    newest_unverified: opencode::newest_unverified_migration,
    reported: Once::new(),
};

/// The database OpenCode reads and writes: `OPENCODE_DB` verbatim when
/// absolute, under the data directory when relative, else
/// `<data>/opencode.db` — the same resolution OpenCode's own
/// `database.ts` performs. Channel-specific databases
/// (`opencode-<channel>.db`) are not searched; the channel is chosen at
/// install time and is not observable from here.
fn database_path_from(
    opencode_db: Option<&str>,
    xdg_data_home: Option<&Path>,
    home: &Path,
) -> PathBuf {
    let data_dir = xdg_data_home
        .filter(|path| !path.as_os_str().is_empty())
        .map(|path| path.join("opencode"))
        .unwrap_or_else(|| home.join(".local").join("share").join("opencode"));
    match opencode_db.filter(|value| !value.is_empty()) {
        Some(value) => {
            let path = PathBuf::from(value);
            if path.is_absolute() {
                path
            } else {
                data_dir.join(path)
            }
        }
        None => data_dir.join("opencode.db"),
    }
}

/// OpenCode resumes and forks by session id — the locator's stem — with
/// resume run in the session's working directory.
struct OpenCodeLauncher;

impl SessionLauncher for OpenCodeLauncher {
    fn resume_command(&self, launch: &SessionLaunch) -> Result<std::process::Command> {
        let mut command = std::process::Command::new("opencode");
        command.arg("--session").arg(session_id_of(launch.path)?);
        if let Some(project_path) = launch.project_path {
            command.current_dir(project_path);
        }
        Ok(command)
    }

    /// A fork runs where the user is now, not where the original session
    /// ran: the branch belongs to the current project.
    fn fork_command(&self, launch: &SessionLaunch) -> Result<std::process::Command> {
        let mut command = std::process::Command::new("opencode");
        command
            .arg("--session")
            .arg(session_id_of(launch.path)?)
            .arg("--fork");
        Ok(command)
    }
}

fn session_id_of(path: &Path) -> Result<String> {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .filter(|stem| stem.starts_with(opencode::SESSION_ID_PREFIX))
        .map(str::to_owned)
        .ok_or_else(|| {
            AppError::ConfigError(format!(
                "{} does not name an OpenCode session",
                path.display()
            ))
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::history::format::opencode::fixture::{self, SessionSpec};
    use crate::history::provider::sqlite::SESSION_DATABASE_LOCKED;
    use std::ffi::OsStr as StdOsStr;

    fn database_in(directory: &Path) -> PathBuf {
        let database = directory.join("opencode.db");
        fixture::create_database(&database);
        database
    }

    fn discovered(database: &Path) -> Vec<SessionStub> {
        OpenCodeStorage
            .discover(&SessionRoot::new(database))
            .unwrap()
            .stubs
    }

    #[test]
    fn the_database_is_opencode_db_or_its_override() {
        let home = Path::new("/home/user");
        assert_eq!(
            database_path_from(None, None, home),
            home.join(".local/share/opencode/opencode.db")
        );
        assert_eq!(
            database_path_from(None, Some(Path::new("/xdg/data")), home),
            Path::new("/xdg/data/opencode/opencode.db")
        );
        assert_eq!(
            database_path_from(Some("/elsewhere/history.db"), None, home),
            Path::new("/elsewhere/history.db")
        );
        assert_eq!(
            database_path_from(Some("beta.db"), None, home),
            home.join(".local/share/opencode/beta.db"),
            "a relative override joins the data directory, as OpenCode joins it"
        );
        assert_eq!(
            database_path_from(Some(""), None, home),
            home.join(".local/share/opencode/opencode.db"),
            "an empty override means unset"
        );
    }

    /// The `time_updated` of the archived fixture session; its stub's
    /// `modified` comes from this column.
    const ARCHIVED_SESSION_UPDATED_MS: i64 = 1755000000000;

    /// A session OpenCode has archived, with no messages of its own.
    fn archived_session(connection: &Connection, session_id: &str) {
        fixture::insert_session(
            connection,
            &SessionSpec {
                id: session_id,
                parent_id: None,
                directory: "/tmp/opencode-project",
                title: "archived away",
                created_ms: 1754999900000i64,
                updated_ms: ARCHIVED_SESSION_UPDATED_MS,
                archived_ms: Some(1755000500000i64),
            },
        );
    }

    #[test]
    fn discovery_lists_archived_sessions_with_the_others() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_live");
        archived_session(&connection, "ses_archived");
        drop(connection);

        let stubs = discovered(&database);

        assert_eq!(
            stubs
                .iter()
                .map(|stub| stub.cache_key.as_str())
                .collect::<Vec<_>>(),
            vec!["ses_archived", "ses_live"],
            "an archived session is still a session to browse"
        );
        assert_eq!(stubs[0].locator, database.join("ses_archived.jsonl"));
        assert_eq!(
            stubs[0].fingerprint.modified,
            Some(UNIX_EPOCH + Duration::from_millis(ARCHIVED_SESSION_UPDATED_MS as u64)),
            "the archived row's own time_updated fingerprints its stub"
        );
    }

    #[test]
    fn a_missing_database_discovers_nothing() {
        let directory = tempfile::tempdir().unwrap();
        let stubs = discovered(&directory.path().join("never-created.db"));
        assert!(stubs.is_empty());
    }

    /// The fingerprint is the cache's change detector: new rows and renames
    /// must move it, an untouched database must not.
    #[test]
    fn the_fingerprint_moves_with_content_and_title_but_not_on_its_own() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_fingerprint");

        let first = discovered(&database)[0].fingerprint;
        let second = discovered(&database)[0].fingerprint;
        assert_eq!(first, second, "an untouched database fingerprints alike");

        fixture::insert_message(
            &connection,
            "msg_more",
            "ses_fingerprint",
            1755000600000i64,
            &serde_json::json!({ "role": "user", "time": { "created": 1755000600000i64 } }),
        );
        let after_append = discovered(&database)[0].fingerprint;
        assert_ne!(first, after_append, "appended rows must reparse");

        OpenCodeProvider
            .rename_session(&database.join("ses_fingerprint.jsonl"), "renamed")
            .unwrap();
        let after_rename = discovered(&database)[0].fingerprint;
        assert_ne!(after_append, after_rename, "a rename must reparse");
    }

    #[test]
    fn resume_and_fork_take_the_session_id_from_the_locator() {
        let path = PathBuf::from("/data/opencode/opencode.db/ses_launch.jsonl");
        let project = PathBuf::from("/tmp/project");
        let launch = SessionLaunch {
            path: &path,
            project_path: Some(&project),
            configured_args: &["--claude-only".to_owned()],
        };
        let launcher = Source::OpenCode.provider().launcher();

        let resume = launcher.resume_command(&launch).unwrap();
        assert_eq!(resume.get_program(), StdOsStr::new("opencode"));
        assert_eq!(
            resume.get_args().collect::<Vec<_>>(),
            vec![StdOsStr::new("--session"), StdOsStr::new("ses_launch")],
            "opencode resumes by session id and must not inherit Claude's configured arguments"
        );
        assert_eq!(resume.get_current_dir(), Some(project.as_path()));

        let fork = launcher.fork_command(&launch).unwrap();
        assert_eq!(
            fork.get_args().collect::<Vec<_>>(),
            vec![
                StdOsStr::new("--session"),
                StdOsStr::new("ses_launch"),
                StdOsStr::new("--fork")
            ]
        );
        assert_eq!(
            fork.get_current_dir(),
            None,
            "a fork runs in the current directory"
        );
    }

    #[test]
    fn rename_updates_the_title_and_preserves_the_rest_of_the_row() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_rename");
        drop(connection);
        let locator = database.join("ses_rename.jsonl");

        OpenCodeProvider
            .rename_session(&locator, "renamed\nOpenCode")
            .unwrap();

        let connection = Connection::open(&database).unwrap();
        let (title, slug, version): (String, String, String) = connection
            .query_row(
                "SELECT title, slug, version FROM session WHERE id = 'ses_rename'",
                [],
                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
            )
            .unwrap();
        assert_eq!(title, "renamed OpenCode");
        assert_eq!(
            slug, "ses_rename",
            "columns this browser does not own survive"
        );
        assert_eq!(version, "1.0.0-fixture");
        drop(connection);

        let reparsed = OPENCODE_DB.parse_transcript(&locator).unwrap().unwrap();
        assert_eq!(reparsed.title.as_deref(), Some("renamed OpenCode"));
    }

    #[test]
    fn delete_cascades_to_the_sessions_messages_and_parts() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_doomed");
        fixture::standard_session(&connection, "ses_kept");
        drop(connection);

        OpenCodeProvider
            .delete_session(&database.join("ses_doomed.jsonl"))
            .unwrap();

        let connection = Connection::open(&database).unwrap();
        let count = |sql: &str| -> i64 { connection.query_row(sql, [], |row| row.get(0)).unwrap() };
        assert_eq!(
            count("SELECT COUNT(*) FROM session WHERE id = 'ses_doomed'"),
            0
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM message WHERE session_id = 'ses_doomed'"),
            0,
            "messages cascade with their session"
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM part WHERE session_id = 'ses_doomed'"),
            0,
            "parts cascade with their session"
        );
        assert_eq!(
            count("SELECT COUNT(*) FROM session WHERE id = 'ses_kept'"),
            1
        );
    }

    /// A sub-agent session of `parent_id` with one assistant message and one
    /// part.
    fn subagent_session(connection: &Connection, session_id: &str, parent_id: &str) {
        fixture::insert_session(
            connection,
            &SessionSpec {
                id: session_id,
                parent_id: Some(parent_id),
                directory: "/tmp/opencode-project",
                title: "sub-agent task",
                created_ms: 1755000200000i64,
                updated_ms: 1755000300000i64,
                archived_ms: None,
            },
        );
        let message_id = format!("msg_{session_id}");
        fixture::insert_message(
            connection,
            &message_id,
            session_id,
            1755000200000i64,
            &serde_json::json!({ "role": "assistant", "time": { "created": 1755000200000i64 } }),
        );
        fixture::insert_part(
            connection,
            &format!("prt_{session_id}"),
            &message_id,
            session_id,
            1755000200000i64,
            &serde_json::json!({ "type": "text", "text": "sub-agent answer" }),
        );
    }

    /// `parent_id` carries no foreign key, so a sub-agent session would
    /// survive its parent's delete and list as a session the user never
    /// started.
    #[test]
    fn delete_removes_every_subagent_session_with_the_session() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_parent");
        subagent_session(&connection, "ses_subagent", "ses_parent");
        subagent_session(&connection, "ses_nested", "ses_subagent");
        fixture::standard_session(&connection, "ses_kept");
        drop(connection);

        let deleted = OpenCodeProvider
            .delete_session(&database.join("ses_parent.jsonl"))
            .unwrap();

        assert_eq!(
            deleted,
            Deleted {
                stored_copies: 1,
                subagent_sessions: 2,
            }
        );
        let connection = Connection::open(&database).unwrap();
        let rows = |table: &str, session_column: &str, session_id: &str| -> i64 {
            connection
                .query_row(
                    &format!("SELECT COUNT(*) FROM {table} WHERE {session_column} = ?1"),
                    [session_id],
                    |row| row.get(0),
                )
                .unwrap()
        };
        for session_id in ["ses_parent", "ses_subagent", "ses_nested"] {
            for (table, session_column) in [
                ("session", "id"),
                ("message", "session_id"),
                ("part", "session_id"),
            ] {
                assert_eq!(
                    rows(table, session_column, session_id),
                    0,
                    "{session_id} kept {table} rows"
                );
            }
        }
        assert_eq!(rows("session", "id", "ses_kept"), 1);
        assert!(rows("message", "session_id", "ses_kept") > 0);
    }

    /// A row can name any session as its parent, one of its own sub-agent
    /// sessions included; the walk must not follow such a chain for ever.
    #[test]
    fn a_parent_chain_that_loops_back_on_the_session_terminates() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        subagent_session(&connection, "ses_parent", "ses_nested");
        subagent_session(&connection, "ses_subagent", "ses_parent");
        subagent_session(&connection, "ses_nested", "ses_subagent");
        drop(connection);

        let deleted = OpenCodeProvider
            .delete_session(&database.join("ses_parent.jsonl"))
            .unwrap();

        assert_eq!(
            deleted,
            Deleted {
                stored_copies: 1,
                subagent_sessions: 2,
            }
        );
        let connection = Connection::open(&database).unwrap();
        let remaining: i64 = connection
            .query_row("SELECT COUNT(*) FROM session", [], |row| row.get(0))
            .unwrap();
        assert_eq!(remaining, 0);
    }

    #[test]
    fn the_write_path_never_creates_a_database() {
        let directory = tempfile::tempdir().unwrap();
        let vanished = directory.path().join("vanished.db");

        assert!(open_read_write(&vanished).is_err());
        assert!(
            !vanished.exists(),
            "an absent database must fail the write, not be created by it"
        );
    }

    #[test]
    fn a_file_opencode_does_not_own_survives_delete() {
        let directory = tempfile::tempdir().unwrap();
        let pi = directory.path().join("session.jsonl");
        std::fs::copy(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/pi/v3-branched.jsonl"),
            &pi,
        )
        .unwrap();

        assert!(OpenCodeProvider.delete_session(&pi).is_err());
        assert!(pi.exists());

        let database = database_in(directory.path());
        assert!(
            OpenCodeProvider
                .delete_session(&database.join("ses_absent.jsonl"))
                .is_err(),
            "a session the database does not hold is not OpenCode's to delete"
        );
    }

    /// A rename rewrites only database rows; the fingerprint carries it to
    /// the next load, with no sidecar overlay to fall back on.
    #[test]
    fn a_rename_reaches_the_next_load_through_a_warm_cache() {
        use crate::history::cache::SessionCacheStore;
        use crate::history::provider::load_sessions_with_cache;

        let directory = tempfile::tempdir().unwrap();
        let cache_base = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_warm");
        drop(connection);

        let storage = crate::history::provider::storage::RootedStorage {
            inner: OpenCodeStorage,
            root: SessionRoot::new(&database).in_agent_tree(),
        };
        let cache = SessionCacheStore::under(cache_base.path(), storage.cache());
        let first = load_sessions_with_cache(&storage, &cache, false, None).unwrap();
        assert_eq!(
            first[0].custom_title.as_deref(),
            Some("fixture generated title")
        );

        OpenCodeProvider
            .rename_session(&database.join("ses_warm.jsonl"), "fresh name")
            .unwrap();

        let second = load_sessions_with_cache(&storage, &cache, false, None).unwrap();
        assert_eq!(second[0].custom_title.as_deref(), Some("fresh name"));
    }

    #[test]
    fn a_session_id_resolves_to_its_row_whether_or_not_it_is_archived() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_live");
        archived_session(&connection, "ses_archived");
        drop(connection);

        assert_eq!(
            stored_session_in(&database, "ses_live")
                .unwrap()
                .map(|stub| stub.locator),
            Some(database.join("ses_live.jsonl"))
        );
        assert_eq!(
            stored_session_in(&database, "ses_archived")
                .unwrap()
                .map(|stub| stub.locator),
            Some(database.join("ses_archived.jsonl")),
            "an archived session is still reachable by its id"
        );
        assert!(
            stored_session_in(&database, "ses_absent")
                .unwrap()
                .is_none()
        );
    }

    /// One stub per session, its sub-agent rows named on it, nested ones
    /// flattened, and the fingerprint spanning all of them.
    #[test]
    fn discovery_names_each_sessions_sub_agent_rows() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_parent");
        subagent_session(&connection, "ses_subagent", "ses_parent");
        subagent_session(&connection, "ses_nested", "ses_subagent");
        fixture::standard_session(&connection, "ses_other");
        drop(connection);

        let stubs = discovered(&database);

        assert_eq!(
            stubs
                .iter()
                .map(|stub| (stub.cache_key.as_str(), stub.subagents.clone()))
                .collect::<Vec<_>>(),
            vec![
                ("ses_other", vec![]),
                (
                    "ses_parent",
                    vec![
                        database.join("ses_nested.jsonl"),
                        database.join("ses_subagent.jsonl"),
                    ]
                ),
            ]
        );
        assert!(
            stubs[1].fingerprint.size > stubs[0].fingerprint.size,
            "the parent's fingerprint spans its sub-agent rows"
        );
        assert_eq!(
            stubs[1].fingerprint.modified,
            Some(UNIX_EPOCH + Duration::from_millis(1755000400000)),
            "the newest time_updated across the session and its sub-agents"
        );
        assert_eq!(
            stored_session_in(&database, "ses_parent").unwrap().as_ref(),
            Some(&stubs[1]),
            "session-id lookup answers with discovery's stub, fingerprint included"
        );

        let subagent = stored_session_in(&database, "ses_subagent")
            .unwrap()
            .unwrap();
        assert_eq!(
            subagent.subagents,
            vec![database.join("ses_nested.jsonl")],
            "a sub-agent row's id resolves to a stub of its own with the rows beneath it"
        );
    }

    /// A row naming a parent the database no longer holds is the only record
    /// of its conversation, so it lists as a session.
    #[test]
    fn a_sub_agent_session_whose_parent_is_absent_lists_as_a_session() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        subagent_session(&connection, "ses_orphan", "ses_gone");
        drop(connection);

        let stubs = discovered(&database);

        assert_eq!(stubs.len(), 1);
        assert_eq!(stubs[0].cache_key, "ses_orphan");
    }

    #[test]
    fn a_query_without_the_session_prefix_resolves_without_opening_a_database() {
        assert_eq!(
            OpenCodeProvider.resolve_session_id("deployment").unwrap(),
            None
        );
    }

    /// The reason of the failure to list `database`.
    fn discover_failure(database: &Path) -> &'static str {
        match OpenCodeStorage.discover(&SessionRoot::new(database)) {
            Err(AppError::SessionListUnreadable { reason, .. }) => reason,
            other => panic!("expected an unusable database, got {other:?}"),
        }
    }

    /// A present database that cannot be read fails the load with the reason
    /// Codex's list reports, so the `Ctrl+L` list shows it rather than
    /// `--debug` alone.
    #[test]
    fn a_present_database_that_cannot_be_read_fails_the_load() {
        let directory = tempfile::tempdir().unwrap();
        let database = directory.path().join("opencode.db");

        std::fs::write(&database, "not sqlite at all").unwrap();
        assert_eq!(
            discover_failure(&database),
            SESSION_DATABASE_CANNOT_BE_READ,
            "a file that is not a database"
        );

        std::fs::remove_file(&database).unwrap();
        Connection::open(&database)
            .unwrap()
            .execute_batch("CREATE TABLE migration (id text PRIMARY KEY)")
            .unwrap();
        assert_eq!(
            discover_failure(&database),
            SESSION_DATABASE_CANNOT_BE_READ,
            "a database without the session table"
        );
    }

    /// OpenCode holds the database while it writes. The reader waits the busy
    /// timeout for the lock, then fails as locked.
    #[test]
    fn a_locked_database_fails_the_load_as_locked_after_the_busy_wait() {
        let directory = tempfile::tempdir().unwrap();
        let database = database_in(directory.path());
        let connection = Connection::open(&database).unwrap();
        fixture::standard_session(&connection, "ses_held");
        drop(connection);
        let writer = Connection::open(&database).unwrap();
        writer
            .pragma_update(None, "locking_mode", "EXCLUSIVE")
            .unwrap();
        writer
            .execute("UPDATE session SET title = 'held'", [])
            .unwrap();

        let failure = discover_in(&database, Duration::from_millis(50));

        match failure {
            Err(AppError::SessionListUnreadable { reason, .. }) => {
                assert_eq!(reason, SESSION_DATABASE_LOCKED);
            }
            Err(other) => panic!("expected a locked database, got {other}"),
            Ok(discovered) => panic!(
                "expected a locked database, got {} sessions",
                discovered.stubs.len()
            ),
        }
    }

    /// Session-ID lookup and delete read the same rows the list does, so a
    /// database they cannot read fails with the list's reason, delete before
    /// any row is removed.
    #[test]
    fn lookup_and_delete_with_a_database_they_cannot_read_fail_with_the_lists_reason() {
        let directory = tempfile::tempdir().unwrap();
        let database = directory.path().join("opencode.db");
        std::fs::write(&database, "not sqlite at all").unwrap();

        let lookup = stored_session_in(&database, "ses_x").unwrap_err();
        let delete = OpenCodeProvider
            .delete_session(&database.join("ses_x.jsonl"))
            .unwrap_err();

        for failure in [lookup, delete] {
            assert!(
                matches!(
                    failure,
                    AppError::SessionListUnreadable {
                        reason: SESSION_DATABASE_CANNOT_BE_READ,
                        ..
                    }
                ),
                "{failure}"
            );
        }
        assert_eq!(
            std::fs::read_to_string(&database).unwrap(),
            "not sqlite at all",
            "the delete wrote nothing"
        );
    }
}
