use crate::agent::sanitize::sanitize_agent_text;
use crate::history::format::trim_blank_lines;
use crate::history::skill_text::{skill_directory, skill_name};
use crate::log_entry::{ContentBlock, UserContent};
use crate::tui::{parse_command_name, parse_command_name_and_args};

/// The text a user message shows: each text block through
/// [`process_command_message`], joined by a blank line. `None` when no block
/// shows anything.
pub(crate) fn user_text(content: &UserContent) -> Option<String> {
    match content {
        UserContent::String(text) => process_command_message(text),
        UserContent::Blocks(blocks) => {
            let texts: Vec<String> = blocks
                .iter()
                .filter_map(|block| match block {
                    ContentBlock::Text { text } => process_command_message(text),
                    _ => None,
                })
                .collect();
            (!texts.is_empty()).then(|| texts.join("\n\n"))
        }
    }
}

/// Process user message text to handle command-related XML tags.
/// Returns None if the message should be skipped entirely (e.g., empty local-command-stdout).
pub(crate) fn process_command_message(text: &str) -> Option<String> {
    let trimmed = text.trim();

    // Check for local-command-caveat - skip these system messages entirely
    if trimmed.starts_with("<local-command-caveat>") && trimmed.ends_with("</local-command-caveat>")
    {
        return None;
    }

    if let Some(output) = local_command_stdout(trimmed) {
        return Some(output).filter(|output| !output.is_empty());
    }

    // Check if this is a command message with <command-name> tag
    if let Some(command_name) = parse_command_name(trimmed) {
        // Skip /clear commands - internal context-clearing, not meaningful to display
        if command_name == "/clear" {
            return None;
        }

        return parse_command_name_and_args(trimmed);
    }

    if let Some(directory) = skill_directory(trimmed) {
        let name = skill_name(directory).unwrap_or("invoked");
        return Some(format!("*Skill: {name}*"));
    }

    Some(text.to_string())
}

/// The output of a slash command (`/compact`, `/add-dir`, …) that Claude Code
/// recorded wrapped in `<local-command-stdout>`, with the terminal styling it
/// wrote around that output removed and the blank lines at either end dropped.
/// `None` when `text` is not such a wrapper; empty when the command printed
/// nothing.
pub(crate) fn local_command_stdout(text: &str) -> Option<String> {
    let inner = text
        .strip_prefix("<local-command-stdout>")?
        .strip_suffix("</local-command-stdout>")?;
    Some(trim_blank_lines(&sanitize_agent_text(inner)).to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn process_command_message_skips_local_command_caveat() {
        let caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
        assert_eq!(process_command_message(caveat), None);
    }

    #[test]
    fn process_command_message_skips_local_command_caveat_with_whitespace() {
        let caveat = "  <local-command-caveat>Some caveat text</local-command-caveat>  ";
        assert_eq!(process_command_message(caveat), None);
    }

    #[test]
    fn process_command_message_preserves_normal_text() {
        assert_eq!(
            process_command_message("Hello world"),
            Some("Hello world".to_string())
        );
    }

    #[test]
    fn process_command_message_skips_empty_stdout() {
        assert_eq!(
            process_command_message("<local-command-stdout></local-command-stdout>"),
            None
        );
        assert_eq!(
            process_command_message("<local-command-stdout>   </local-command-stdout>"),
            None
        );
    }

    #[test]
    fn process_command_message_extracts_nonempty_stdout() {
        assert_eq!(
            process_command_message("<local-command-stdout>output here</local-command-stdout>"),
            Some("output here".to_string())
        );
    }

    #[test]
    fn process_command_message_removes_terminal_styling_from_stdout() {
        assert_eq!(
            process_command_message(
                "<local-command-stdout>\u{1b}[2mCompacted (ctrl+o to see full summary)\u{1b}[22m</local-command-stdout>"
            ),
            Some("Compacted (ctrl+o to see full summary)".to_string())
        );
        assert_eq!(
            process_command_message(
                "<local-command-stdout>\u{1b}[1mC:\\lane-1\u{1b}[22m is already added as a working directory.</local-command-stdout>"
            ),
            Some("C:\\lane-1 is already added as a working directory.".to_string())
        );
    }

    #[test]
    fn process_command_message_skips_stdout_that_is_only_terminal_styling() {
        assert_eq!(
            process_command_message(
                "<local-command-stdout>\u{1b}[2m\u{1b}[22m</local-command-stdout>"
            ),
            None
        );
    }

    #[test]
    fn process_command_message_skips_clear_command() {
        assert_eq!(
            process_command_message("<command-name>/clear</command-name>"),
            None
        );
        // Also skip clear with command-message and command-args tags
        assert_eq!(
            process_command_message(
                "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"
            ),
            None
        );
    }

    #[test]
    fn process_command_message_extracts_other_command_names() {
        assert_eq!(
            process_command_message("<command-name>/help</command-name>"),
            Some("/help".to_string())
        );
    }

    #[test]
    fn process_command_message_condenses_skill_invocation() {
        let skill_msg = "Base directory for this skill: /Users/raine/.claude/skills/consult\n\nConsult an external LLM with the user's query.\n\n**Arguments:** `how to add more aliases?`";
        assert_eq!(
            process_command_message(skill_msg),
            Some("*Skill: consult*".to_string())
        );
        let windows_skill_msg =
            "Base directory for this skill: C:\\Users\\u\\.claude\\skills\\consult\n\n# Consult";
        assert_eq!(
            process_command_message(windows_skill_msg),
            Some("*Skill: consult*".to_string())
        );
    }

    #[test]
    fn process_command_message_skill_invocation_fallback() {
        let skill_msg = "Base directory for this skill:";
        assert_eq!(
            process_command_message(skill_msg),
            Some("*Skill: invoked*".to_string())
        );
    }
}
